### PR TITLE
added all architectures

### PR DESCRIPTION
**Pull request by vinny1575**

### CODE REVIEW

**Comment by jhansireddy** [comment]
@vinny1575 Thanks for the pull request for generating it for all the platforms, It would be great if you could please check in your changes if there are any in Application.mk or Android.mk which are relevant for generating the libraries for all the platforms as part of this pull request.

**Comment by vinny1575** [comment]
There were no changes. I ran ndk-build as is. Application.mk already has "APP_ABI := all" set.

**Comment by jhansireddy** [comment]
@vinny1575 I see two new directories mips64 and x86_64 in your pull request which I was not able to generate with the current application.mk which already has "APP_ABI := all". Are they for 64 bit architecture? What is the relevance of them?

**Comment by vinny1575** [comment]
Yes for 64bit architecture. I needed it for the Galaxy S6 and S7 support.

**Comment by MarsVard** [comment]
@vinny1575  How did you get arm64-v8a/libopencv_java3.so to build?

**Pull request closed without merging**
