### PR TITLE
Fix android manifest for Android X migration

### PR DESCRIPTION
**Pull request by davidlutta**

### CODE REVIEW

**Comment by KavinNallasamy** [comment]
Hi.....did you solved this issue?

**Comment by davidlutta** [comment]
Hi 
Migrated the library to androidX then replaced this line in the androidmanifest
`android:name="android.support.v4.content.FileProvider"`
with
`android:name="androidx.core.content.FileProvider"
`

**Comment by KavinNallasamy** [comment]
Thank you,
And I have another one issue, getting crash while opening camera in target api 29.
can you help me?

**Comment by davidlutta** [comment]
Please post the error message and stacktrace

**Comment by Vivek-shetty** [comment]
Hi @davidlutta,

app getting crashes while opening camera in target api 29.

crash occurred while inserting bitmap to MediaStore

String path = MediaStore.Images.Media.insertImage(context.getContentResolver(), bitmap, "Title", null);

MediaStore: Failed to insert image java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at android.provider.MediaStore$PendingSession.<init>(MediaStore.java:756)
        at android.provider.MediaStore.openPending(MediaStore.java:630)
        at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:1772)
        at com.scanlibrary.Utils.getUri(Utils.java:30)
        at com.scanlibrary.PickImageFragment.onActivityResult(PickImageFragment.java:287)
        at android.app.Activity.dispatchActivityResult(Activity.java:8137)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by jhansireddy** [comment]
@davidlutta Already migrated to AndroidX. However, Thank you for the PR

**Pull request closed without merging**
