### PR TITLE
Add native librairies to support 64 bit architectures with OpenCV 3.1

### PR DESCRIPTION
**Pull request by neoscreenager**
Build scan.cpp for generating shared libraries to support 64 bit architectures with OpenCV 3.1 .
The demo could be executed now on 64 bit devices and emulators.

### CODE REVIEW

**Comment by HappyDr0id** [comment]
Your fork is actually not working on my devices : a Moto E on Android 4.4.4 and a Moto X on Android 6.0. Both of them are on the armeabi-v7a platform.

It seems that it doesn't find some .so files. I also tried with OpenCV 3.0 and I got the same errors.

On the Moto E :
java.lang.UnsatisfiedLinkError: Couldn't load opencv_java from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.scanner.demo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.scanner.demo-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                      at java.lang.System.loadLibrary(System.java:526)
                                                                      at com.scanlibrary.ScanActivity.<clinit>(ScanActivity.java:73)
                                                                      at java.lang.Class.newInstanceImpl(Native Method)
                                                                      at java.lang.Class.newInstance(Class.java:1208)
                                                                      at android.app.Instrumentation.newActivity(Instrumentation.java:1084)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2115)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5086)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                      at dalvik.system.NativeStart.main(Native Method)

and on the Moto X :
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.scanner.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.scanner.demo-1/lib/arm, /data/app/com.scanner.demo-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libopencv_java.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                      at com.scanlibrary.ScanActivity.<clinit>(ScanActivity.java:73)
                                                                      at java.lang.Class.newInstance(Native Method)
                                                                      at android.app.Instrumentation.newActivity(Instrumentation.java:1090)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by HappyDr0id** [comment]
I have found the solution : you have to use the OpenCVLoader class to load OpenCV 3.1, otherwise it will crash saying that it doesn't find the library.
You can find how to integrate the OpenCVSDK to your project to use OpenCVLoader : http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.html#application-development-with-static-initialization.

This way, instead of System.loadLibrary("opencv_java"), you will load the library with OpenCVLoader.initDebug().

**Comment by delkant** [comment]
System.loadLibrary("opencv_java3") just add the version 3 and you will also solve the problem.

**Comment by f0restgump92** [comment]
Will this work on other platforms than armeabi-v7a?

**Comment by delkant** [comment]
I have no problems on x86, I haven't tried other.

**Comment by f0restgump92** [comment]
Yeah nice, this is awesome, i only had arm in my libs

**Comment by xzeman43** [comment]
Hello, after last Android studio and gradle update, I am all back in the same issue with unsatisfied link error.

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cz.vutbr.krystofzeman.jaspar-1.apk"],nativeLibraryDirectories=[/data/app-lib/cz.vutbr.krystofzeman.jaspar-1, /vendor/lib, /system/lib]]] couldn't find "libopencv_java3.so"
at java.lang.Runtime.loadLibrary(Runtime.java:373)
at java.lang.System.loadLibrary(System.java:540)
at com.scanlibrary.ScanActivity.<clinit>(ScanActivity.java:73)
 at java.lang.Class.newInstanceImpl(Native Method)
 at java.lang.Class.newInstance(Class.java:1215)
at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2280)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
at android.app.ActivityThread.access$800(ActivityThread.java:166)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5387)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
at dalvik.system.NativeStart.main(Native Method)

I tried to fix it with all "solutions" I found (i.e. http://stackoverflow.com/questions/24357687/how-to-include-so-library-in-android-studio). Still no luck... Can someone please have a look and suggest me some solution? I really do not se any reason, why it cannot see the libraries...

**Comment by jhansireddy** [comment]
@neoscreenager Thanks for the pull request, I have upgraded the opencv to 3.1 and also building the libraries for all platforms.

**Comment by xzeman43** [comment]
Thank you very much. I actually already upgraded it to newest OpenCV and
also stripped it from unnecessary libraries methods... But this project
helped me a lot while I was looking for a starting point :)

Dne 16. 10. 2016 19:34 napsal uživatel "Jhansi Karee" <
notifications@github.com>:

**Pull request closed without merging**
